## Site settings
#title: Nyonura
#email: dondeng2@gmail.com
#description: > # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
#baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: donden1
#github_username:  dondeng
#
## Build settings
#markdown: kramdown
name:   'Nyonura'
url:    'http://nyonura.com'
author: 'Dennis Ondeng'

include:  ['_pages']

paginate:      10
paginate_path: '/blog/page:num/'
permalink:     '/blog/:year/:title/'
relative_permalinks: false

excerpt_separator: "{{ more }}"

safe:     true
pygments: false
markdown: 'kramdown'
timezone: 'Africa/Nairobi'